[project]
name = "aitools"
version = "0.1.0"
description = "Tools using LLM AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.24",
    "langchain[openai]>=0.3.24",
    "mcp[cli]>=1.6.0",
    "word-forms>=2.1.0",
]
