[project]
name = "aitools"
version = "0.1.0"
description = "Tools using LLM AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain[openai]>=0.3.24",
]
